### ISSUE TITLE
CMSIS FFT Functions

### ISSUE THREAD

**Issue by emrealabay** [MaximIntegratedAI/MAX78000_SDK#44]
I'm trying to calculate FFT using "arm_rfft_fast_f32" which is included in arm_math.h. When i compile project it gives undefined reference error. After i have checked " C:\MaximSDK\Libraries\CMSIS "folder, i realized there was header file for arm_math.h but source files were missing. So i copied source files from " https://github.com/ARM-software/CMSIS/tree/master/CMSIS/DSP_Lib/Source "  repo and added it as linked resources to project. But it did not help. 
Can anyone help?

**Comment by rotx-maxim** [comment]
Building CMSIS can be tricky. You did not show the exact error messages you're getting, so I can give you only the workarounds I've come across (no guarantees that this will work under all circumstances):
1. I use CMSIS_5 from https://github.com/ARM-software/CMSIS_5.git
2. Rather than building CMSIS as a library, you can copy the source files and add them to "`SRCS`" in your MAX78000 Makefile. For example:
`SRCS+=arm_rfft_fast_f32.c`
3. Add the following to your MAX78000 Makefile, adjusting the CMSIS install path as needed:
`PROJ_CFLAGS+=-I. -ICMSIS/Core/Include -I../../CMSIS_5/CMSIS/NN/Include -I../../CMSIS_5/CMSIS/DSP/Include -DCMSIS_VECTAB_VIRTUAL`
4. Add an empty file named `cmsis_vectab_virtual.h` to your source directory.

The project should now build with all MAX78000 peripheral libraries (you may need multiple iterations until you've collected all CMSIS source files that are referenced by `arm_rfft_fast_f32`).

Please let us know if this helps.
