### ISSUE TITLE
OpenOCD finishing but not showing the INFO: localhost:3333, can't load new examples onto board

### ISSUE THREAD

**Issue by Lockbox36** [MaximIntegratedAI/MAX78000_SDK#59]
Hey Maxim Devs,

Similar to some other issue's I've read, I believe my hardware is stuck in a bit of a soft-sleep or something. I currently have the FaceID Demo loaded onto my MAX78000EV, and can tell it's working correctly since the camera is outputting to the screen and all functionality is there. I've tried reloading multiple new examples onto the board, and have done the same process of OpenOCD window and GNU window in the example path, but my issue is that the PICO debugger doesn't open localhost:3333 in OpenOCD. I've tried resetting the board and quickly redoing the command to see if I can get OpenOCD to start within the 2 second debug window, and have tried resetting the PICO by putting it into maintenance and dragging the new bin. I'm not sure what else I can do to debug, so any suggestions will be appreciated.

**Comment by Jake-Carter** [comment]
Hello, can you provide the full OpenOCD output log?

One thing that usually does the trick (if the problem is firmware/LP lockout-related) is hard-wiping the flash memory.  See ["How to Unlock a MAX78000 that Can No Longer Be Programmed"](https://github.com/MaximIntegratedAI/MaximAI_Documentation/tree/master/MAX78000_Evaluation_Kit#how-to-unlock-a-max78000-that-can-no-longer-be-programmed)

Otherwise, I'll need to see the log output to troubleshoot

**Comment by Lockbox36** [comment]
Hey, so I attempted running the 'Unlock a MAX78000...', got the maintenance mode and whatnot, but it didn't seem to help. I noticed that maybe the DAPLINK bin file provided might be out of date, as I saw it wasn't lining up to one of the texts posted in another issue (or it is up to date and that screenshot was older). Also, the bin file provided has my PICO reboot and the url says feather, not the ev-kit (again, not sure if this matters). 

This is all I see on the OpenOCD side:

Open On-Chip Debugger 0.10.0+dev-g90939caf-dirty (2020-05-20-17:20)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: FW Version = 1.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 0 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 0
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz

I don't see an exact log text file if that's what you meant. It prints out the last "Info : clock speed 2000 kHz" line, then just returns for user input to the command prompt.

**Comment by Lockbox36** [comment]
Forgot to mention - I tried the erase.act (which might actually fix the issue), but when I copied it over the windows explorer was just showing 0% copied and froze up. I don’t know if this is the intended process and it takes time for the erase to actually happen, but I let it sit for about 10 minutes and nothing changed so I stopped the copy process.

**Comment by Jake-Carter** [comment]
Thanks @Lockbox36,

Yes, this is the right OpenOCD log.

It does sound like something is going wrong in the OpenOCD -> debugger -> micro pipeline.  I've seen OpenOCD quit with no error message in the past if the debugger isn't connected to the micro, the board isn't powered on, lockout in firmware, etc.  I've also seen this caused by issues in the actual OpenOCD binaries and config files, debugger firmware, etc.  

Regardless of any issues with OpenOCD, you should be able to wipe the flash memory and start from a clean slate, so let's start trouleshooting that first.

- [This ](https://github.com/MaximIntegratedMicros/max32625pico-firmware-images/raw/main/bin/max32625_max78000fthr_if_crc_v1.0.2.bin) is the correct PICO debugger firmware to use, and it sounds like this is what you've used.  Just to confirm, can you attach the "DETAILS.TXT" file inside of the "DAPLINK" drive to this issue?
- With the above PICO firmware flashed, confirm that "automation allowed" is set to 1 in "DETAILS.TXT"
- With "automation allowed" set to 1, dragging and dropping and empty "erase.act" file onto the DAPLINK drive (with the PICO properly connected) should wipe the flash memory in all but the most extreme lockouts.  It should have no problem wiping the faceID demo, and the progress bar should immediately start.  If you have to wait more than 30s for the process to complete, there is a deeper issue.
- "Properly connected" in this instance means the EVKIT is powered on and the PICO debugger is connected to JH5 on the EVKIT.  JH5 is used for the M4 core, and JH4 is used for the RISC-V core.  Please confirm the connection is being made to JH5.

Can you also confirm the OS you're using?  I see that the OpenOCD version from your log is slightly outdated, and we may need to get our binaries updated on Github.

**Comment by Jake-Carter** [comment]
No problem at all!  I mentioned it because I've done the exact same thing myself.  Glad it was a quick fix.
